#=========================================
#================= server config
#=========================================
server:
  port: 8180
  context-path: /es
  tomcat:
    uri-encoding: UTF-8

#=========================================
#================= spring config
#=========================================
spring:
  profiles:
    active: es
  thymeleaf:
    cache: false